language: groovy
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.m2/"
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
script: "./travis-build.sh"
env:
  global:
  - secure: DK2VCjRlDLGMYEl4dd9Ij3+hg2Gbp/oKaVRq5JGalRU9VC0C6kwoNWeVFjqowuMHU1sFnOxQ4ckaP+3A3IMz6lVoDOvYIi4v3I4QAOdKglRWrzOqgGhoOfKMov0Lmhbe5dVxd3GvzPHzh5QqlXYyOfWFZ5nsAdyh7E/qrnzSk0zh2/FI3CL7peYiB5m/PR6AnLkHF0QFbVBjwEvvXX+0iDuE2AXN+W4mwnERbN1QrbA/koakF5vQdTvT/RZkvAB7exi82LPquyzhWWCGMqKM7hd4xWmIVEMmFkxmfyWZwv/gisWQ5zmzfxGPms7m5O92ftFv9HKgtA7L60D6RnevI9z+O2/b0gvBQ2mxmRDgX0CkAVAae1UwSgZ7hneqt1w1q62Sez4XW1qFSoi0ZMVJfmIyYNPqEFz24GYB3Wj/Kxsiz4vInGkNf99ZtNFpPNc8CaSlfCsRzIk4GyQrm/XuBb9KxTTbdFVSRhfoXHWBW+NPtOxm7esRlTSQ1kw9HH7ThIz3pAsktKQq4TGIEQ9RRLOdD0f7SzA+ClkVZieoL2S7wcLy0x1GlIANg0TaJ89R4rYg1rZTcUDZAEOemH3rGjKFntNT2p5DBHTpr0GItuE2XI57f7GRheJWa/CW7oLagKRcgwlCNv8wrNSeORXFtKCauEBo1XnWuEMWK0sv0ik=
  - secure: pEvANcFQ77UEMCGzSidRhfsAnw/pRqXH3oz4Ck8Dc4bei0VIGDbvohH6ez0xspCQhmifoWKTSz0Rh7JiCjtGZnxqRoPkPDZvwX1zIKOeNg/NK2Wu4QR2KusBYnLanY90nn6qFgFCaJOTbGLcuACox9rtrKtbfcrOk1XBColy4MA9nf8NyHsmxIu89eIISWi8L3gV4Ehv1damAPWgh1infChtwWP4FJvh4nmqhnxD2Gwa7Q87yIDTJWmqgXFTMBRzV6IGGZDbz2oKyENhjeeS8BdiTPThFAcysOLQAJmonbMo8bPtQrmRiTeG/4BSv1jL+q82h+VMrn03Kxr6vpuF4QaOgPbj+DVOkdsk2hpdJN0BQ0EEu8fXj5OhR+jPAUGXQmAzhwPhbBGB6W+0/la/iNDm0xMCqJ0JTHRI88aoeXekArzVVNDOccDirN8K12cuFEwCyMzhIXwiVc78e9xKvIRmhfxhpK87KwObiFY4Jd2rRDNUJ7ySZoruRXf06aTg+dG2j18VykesEToGC9n45dGLXqzI15Mq217pF5NwOoMI/ndy9jZSMWnI5k6V2+jGukYFf3YkKZTvxgYZJKWGQQcU0HEQGQcMJbPpvCHyEmrNKRDqGz5wtZL8Eqg3Un2xTYdxHQaQa1zHLLY9A8ehK0JSpH2tbcuaRqsEC35mX2E=
