language: groovy
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.m2/"
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
script: "./travis-build.sh"
env:
  global:
  - secure: v1R5l0q0lfc1wNxMt8fZtDbqtSOPw0bVGVQucX4Qpv3f4U7KuQPKmg3Y06zU97lxn4kGtvp/NDBfLEC5oNlNa/RW1BXb2K8Gwn+0AAoWG1IwE6bOBuHdHQp2svt2imZh5cGViDpy2VJpSVAaeXKMMFkWZ6ZkPAeqOI3k2sI/FtrND4fpLP6JxlMsADzAvVmWtx3w1XSqgSjR5xflRu8/GQdtZxIFKcIPVmdJvjaYKQyXG9YINRz0sCm7PsT3dW9VzdG2BXCkhJ+ln8QYuIziInNCo9Ant/PXEWy5SpBsOcxS92105hSDoE7dbotOtX6Pc2G0F5YBeL4kXabnS9FJd96CciCDdbzZQjM3DcIZOY1qtorVTge75hOGW3pofsOKDSk+iIBU/AJolWlgXBzLzOmwHNMCDE20EKS9eiKM8mEZt845vJgPIqWzvqnHlSDlUwu4gA4tJMw3QCUQsrPgXUwwHEGhvP/D6wlNTj4S4LhsWfHOca4wTFY/MmwpIf46n4gVDeQgjxpzspb56gce5hF09LeYOQ6i5RWkiHwAgwI1UKsDsrERzbWts76NbZUzkoIT8XQAW2/nmIQ2nsoK32/VfIxcUckrB/rN5TRDgJUVHRc35FLb1yrUd2PjwuFv2VwepzjQXdIpMmdmFdGSuIDBdsZjIPhEU7ZSWW2VgWM=
  - secure: EXSBK0g3L+7hqKjekj+xqP/PLudqGsgh7qtnhw5X22SrzZfB0rf4dUY54L3KIAdcYP0rsCa2sXPGsmyUTgsS+h5bQalWfAP7jXqdQGozbMffAfQbH7KN/VACGMGVfLU5NfFdRK7eZeo1ZzvlYUKBEA8XdU5g4DRRgwoJhp9EpFFRGQKkEkCFJr3mcGg7ceBxS8fP7XoMgvu+vFj0iG14lGA/tmcWfSN81WPPgGi2apPzhF7bsv1klCJqNuA68ql2ob48tdqnWrR6sICj4vwlyNXMWgkTqjR0nG8UiYQviNn2AgfuZU10ICtFl6H5LqOZdH4TlcfW+7aUijtmaqBPMhWy//uERrRYi4jWNMUgY9g6XWvMufpUtaqqlT+5M4qjv+zkHeR39F3aTw/F4tEw/9Yk41Oz1WRiXFcTmNiUjYXkhKz4tAUvsL11jV9QFJi16muNIWnNgK3e8i/OtIU677Yf0ie8+Z6f9Rr6n9ob9becfO0h1Xzdpv2L66q1MG4RSfYpj6kkET+4orhsOUnHKos130+FvLyKyk3T6lKzS2V5Eztr+FhgU4/8YAAgIOlLUdDoCbntfbVfU6Cc9lokI/ONrAlLs6DQI4SREOtq9NfTH3PuH1lYuDTGkY+BiozMNFiEl9lp8+1HRB00zKoSJUv9IpvUaeFshhslgOU5Fsk=
