language: groovy
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.m2/"
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
script: "./travis-build.sh"
env:
  global:
  - secure: IfZSXqVkpWR6R0rTgkcTrtSBrigiWTbVHkS6wq3ydvQ33EhaThj0qPH8XVpZkZiLMJJLc3NkYaaoY2cqTrEkxpltDm2yPynKACccLPxp1fLKVaGItcjtmH/vzDxA4W6HgunYbdA+yZbW72OWj2gjR9CUgtOEiD+dJjsP4uzEE+QsLy1FxPImILKOJ0xmn7iZSJO06rBqGexIQ4ZBPDl6VdqhexIesQUGmRjjbPWSulU0F7CkdRoBsJFjye0D36XvtgU02M/XXt5B3hFSLYTIf+3My6Nck/ISXcPXCNB6KgDkqCGbY0d+HWTqvxndUMTtckkbKmWIcc7pIa66bbuonE96ZKpcL64KvA3/KzsIK+2B6C+QC4v16sZaSsdrQ19F4q/fZcuiqKpJFB1EQfbMw/7GgIivzIxBYQtAU7FdosIM7Y7xrASHj/O5YQirLX+1LBoQXhOI47UlfLEuXb+vwTy9s8ZNned/+YCEgu6exQEnhAVFlKkHydtmJ1J94W3oEw57gPbZ5bU30D2kIO2d/cOzIs6M1LQsZmD87hiQAGTl6lVrX3dtn2fzMQ7GNJPmDiDJ+Ku72nNZVBXNcTNILfY38JWgkOw+71PlkeZPrAefAXjgkx2hfHaTB/uaVXElYfnJrF8NfEaCxOColE+eWdFkbypQPTSGL6Qro/J3yzw=
  - secure: BMYFXGvaeeIUhw6loDCCnTHSutmoBMs9trQNANj6+OWyn7iiskGjvFvCknwKECjQB0yNMLedfJnCJX5BFfRY3f//dnMId1vGL0uiZEuImlcspxbh5a94I/qCv15j1brRLXA3zgWBvP6Wr5htqqj6nmuagW4vcmPKjRLBjfV2/OQIS60fRUmmJwGD/W+brzfcgX3bETunQ//Ml3CxhcjcGwpRdG6SXbg/itU8EzI+nV58q8Y6+UzaByYN3q72cRD3gudQw9LaU3YTckeQD3C5+AYT2cdfNN/YueEAEHBA+nc0bbzoYBfLFuEuKN/eQD8eTBh/tZCKmQEQXNatdL4p1j1NioDWu2F8qX+pvLvSmz6l88/s0pHXJiDizOAeDJtj2OgTLzGRrW9nvM/AcnWPZ+mHDAxwhGhc5Y7HAAgf8aAs2A6xLp/sDbYijHk7HgeStgGIzBhS0yPKj2zVsvinGxy01uKGwYUdxkLEnLrgUUb8r8pbj7UrIOI3tdgliPFGNyM6wkEwezAUnwFPAOl6rC+V8ens5caEJ1vD35G4hkbSQ72k63Gf5xuzSBkviB6pdxkGrZYRgN7Vbp6M5pP++CNOKAD5AsbQUbbMBxW+MT/0k99jZ+2RS2PZeT4abvOwAZ1qXbyToaz+26Tpdy0y4Xk1bU662DBQC6h5hEPOsG4=
