site_name: Grails View Tools
site_description: Grails plugin to help locate views in the spring mvc context
site_author: Sudhir Nimavat
site_url: http://yakworks.github.io/view-tools

pages:
  - Overview: index.md
  - App Resources: app-resources.md

# for the github and edit links
repo_name: yakworks/view-tools
repo_url: https://github.com/yakworks/view-tools
edit_uri: edit/master/docs/

docs_dir: 'docs'
theme: material-components

extra:
  version: 0.10-SNAPSHOT
  palette:
    primary: 'light green'
    accent: indigo

markdown_extensions:
  - pymdownx.extra # replacement for markdown.extensions.extra see https://facelessuser.github.io/pymdown-extensions/extensions/extra/
  - pymdownx.github # untility to add a bunch of others
  - markdown.extensions.sane_lists
  - markdown.extensions.admonition
  - markdown.extensions.codehilite #(guess_lang=false)
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - markdown_include.include:
      base_path: 'docs'
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
