# see defaults options https://github.com/yakworks/gradle-plugins/tree/master/src/main/resources/configs/defaults.yml
title: Grails View Tools
description: |
  ViewResourceLocator for locating views in grails-app/views, plugins, and custom external paths.
  Also GrailsWebEnvironment for binding a mock request is one doesnt exist so that services can operate without a controller
  Used in freemarker and new jasper plugin.
author: Yak.Works
group: org.grails.plugins

github:
  fullName: yakworks/view-tools

team:
  developers: ['basejump: Joshua Burnett']

bintray:
  enabled: true
  # user: ${findAnyProperty("BINTRAY_USER")} //uses System var property
  # key: ${props.findAny("BINTRAY_KEY")} //uses System var property
  pkg:
    repo: grails-plugins
    userOrg: 9ci

maven:
  # repoUrl: http://repo.9ci.com/grails-plugins
  snapshotUrl: http://repo.9ci.com/oss-snapshots
